### ISSUE TITLE
Database functionality not working properly

### ISSUE THREAD

**Issue by wajee-ul-hassan** [runtime-error786/Ecommerce-data_base#1]
i have seen your code because i was working on similar project,but in your database portion you have to use cascade on your tables,because you missed this you code is not working properly

**Comment by runtime-error786** [comment]
I have updated the code. Kindly check it.

**Comment by wajee-ul-hassan** [comment]
> I have updated the code. Kindly check it.

still not working!

**Comment by runtime-error786** [comment]
First, set up the Oracle 19 version on your PC, then run my code. My code is working on my PC, so make sure to input the correct credentials in the 'cred' file.
